server:
  port: 8000


# jdbc 연결
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cb8738oxfvy6.ap-northeast-2.rds.amazonaws.com:3306/back-20220829
    username: lee4339
    password: 1q2w3e4r
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# mybatis 연결
mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:\programing\Junil\Geonho\springboot\springboot-mybatis-20220923/upload/
